package com.sandra.springboot.backend.recetas.models.entity;

// default package
// Generated 25 mar 2023 14:09:12 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Receta generated by hbm2java
 */
@Entity
@Table(name = "receta")
public class Receta implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	@JsonIgnoreProperties({"password","datosUsuario","recetas"})
	private Usuario usuario;
	private String nombre;
	private String tipo;
	private List<String> necesidades;
	private List<String> ingredientes;
	private List<String> elaboracion;
	private int dificultad;
	private String imagen;
	private Date creacion;

	public Receta() {
	}

	public Receta(int id, Usuario usuario, String nombre, String tipo, List<String> ingredientes, List<String> elaboracion,
			int dificultad, String imagen, Date creacion) {
		this.id = id;
		this.usuario = usuario;
		this.nombre = nombre;
		this.tipo = tipo;
		this.ingredientes = ingredientes;
		this.elaboracion = elaboracion;
		this.dificultad = dificultad;
		this.imagen = imagen;
		this.creacion = creacion;
	}

	public Receta(int id, Usuario usuario, String nombre, String tipo, List<String> necesidades, List<String> ingredientes,
			List<String> elaboracion, int dificultad, String imagen, Date creacion) {
		this.id = id;
		this.usuario = usuario;
		this.nombre = nombre;
		this.tipo = tipo;
		this.necesidades = necesidades;
		this.ingredientes = ingredientes;
		this.elaboracion = elaboracion;
		this.dificultad = dificultad;
		this.imagen = imagen;
		this.creacion = creacion;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY) // Le da números consecutivos, un auto-numérico
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "usuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "tipo", nullable = false)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "necesidades")
	public List<String> getNecesidades() {
		return this.necesidades;
	}

	public void setNecesidades(List<String> necesidades) {
		this.necesidades = necesidades;
	}

	@Column(name = "ingredientes", nullable = false)
	public List<String> getIngredientes() {
		return this.ingredientes;
	}

	public void setIngredientes(List<String> ingredientes) {
		this.ingredientes = ingredientes;
	}

	@Column(name = "elaboracion", nullable = false)
	public List<String> getElaboracion() {
		return this.elaboracion;
	}

	public void setElaboracion(List<String> elaboracion) {
		this.elaboracion = elaboracion;
	}

	@Column(name = "dificultad", nullable = false)
	public int getDificultad() {
		return this.dificultad;
	}

	public void setDificultad(int dificultad) {
		this.dificultad = dificultad;
	}

	@Column(name = "imagen", nullable = false)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creacion", nullable = false, length = 13)
	public Date getCreacion() {
		return this.creacion;
	}

	public void setCreacion(Date creacion) {
		this.creacion = creacion;
	}

}
